export const environment = {
  production: true,
  firebase: {
    apiKey: 'AIzaSyARHhCjPakpdQUHcVr6t0JlqmZ44PCcXck',
    authDomain: 'gbarena-auth.firebaseapp.com',
    databaseURL: 'https://gbarena-auth.firebaseio.com',
    projectId: 'gbarena-auth',
    storageBucket: 'gbarena-auth.appspot.com',
    messagingSenderId: '1048508896682',
    appId: '1:1048508896682:web:8b4699060609a77bdf87d3',
    measurementId: 'G-H140P4RWDJ'
  },
  sso_url: 'https://auth.gbarena.com',
  credential: true,
  apiUrl: 'https://api.gbarena.com/api',
  auth_apiUrl: 'https://api.gbarena.com/auth/api/v1',
  apiUrl_V1: 'https://api.gbarena.com/api/v1',
  communityApiUrl: 'https://api.community.gbarena.com/api',
  supportApiUrl: 'https://api.support.gbarena.com/api',
  notificationsApiUrl: 'https://api.notifications.gbarena.com/api',
  Image: 'https://d229ik2y8x56hm.cloudfront.net',
  chatApiUrl: 'https://msg.gbarena.com/api',
  Socket: 'https://socket.gba.gg',
  gbUrl: 'https://www.gbarena.com/',
  chat_Socket: 'https://socket.gba.gg',
  organizerUrl: 'https://organizer.gbarena.com',
  storeUrl: 'https://store.gbarena.com/',
  storeApiUrl: 'https://api.gbarena.com/store/api/v0.2',
  searchApiUrl: 'https://api.gbarena.com/search/api',
  socket_key: '463b575d4c45f4a342c0dd12b866eedc493d2f6034ecb42d0d12d5c9ffc36cf8',
  iframe: 'https://iframe.gbarena.com',
  store_domains: ['store.gbarena.com'],
  endPointWhiteList: ['api.gbarena.com', 'api.community.gbarena.com', 'msg.gbarena.com', 'api.notifications.gbarena.com']
};
